services:
  app:
    container_name: app
    user: node
    build:
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - type: bind
        source: .
        target: /home/node/app
      - app_node_modules:/home/node/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
      - reminder_default
    depends_on:
      - db
  db:
    container_name: reminder_db
    image: postgres:16.0
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5432:5432'

volumes:
  app_node_modules:

networks:
  reminder_default:
    external: true
