services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - type: bind
        source: .
        target: /workspace/app
      - node_modules:/workspace/app/node_modules
    command: sh -c "npm run dev"
    networks:
      - default
      - reminder_default
    depends_on:
      - db
  db:
    container_name: reminder_db
    image: postgres:16.0
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  node_modules:

networks:
  reminder_default:
    external: true