version: '3'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  app:
    container_name: 'devcontaier_app'
    build:
      context: .
    restart: always
    tty: true
    working_dir: /workspace
    volumes:
      - type: bind
        source: ../
        target: /workspace
  db:
    container_name: devcontainer_db
    image: postgres:16.0
    volumes:
      - ../db:/var/lib/postgresql/data
    env_file:
      - ../.env
    ports:
      - '5432:5432'